<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BaconTypedArray\Int32Array'         => __DIR__ . '/src/BaconTypedArray/Int32Array.php',
    'BaconTypedArray\AbstractTypedArray' => __DIR__ . '/src/BaconTypedArray/AbstractTypedArray.php',
    'BaconQrCode\Module'                 => __DIR__ . '/Module.php',
);